### ISSUE TITLE
3.18.1: Warning "Cannot patch http-mitm-proxy/lib/ca.js" after update to http-mitm-proxy 1.1.0

### ISSUE THREAD

**Issue by Black-Thunder** [Apollon77/ioBroker.tuya#745]
**Describe the bug**  
After updating the Tuya adapter from 3.17.0 to 3.18.1, the following warning is logged on every adapter start:

`Cannot patch http-mitm-proxy/lib/ca.js: Error: Cannot find module 'http-mitm-proxy/lib/ca.js'`

The adapter itself continues to start successfully and both the local device connection and Cloud MQTT connection work.

It looks like this is caused by the update to `http-mitm-proxy` 1.1.0. The compiled files are now located below `dist/`, while the Tuya adapter still tries to resolve the old path:

`http-mitm-proxy/lib/ca.js`

**To Reproduce**  
1. Update ioBroker.tuya from 3.17.0 to 3.18.1.
2. Start/restart the Tuya adapter instance.
3. Check the adapter log.
4. See the warning:
   `Cannot patch http-mitm-proxy/lib/ca.js: Error: Cannot find module 'http-mitm-proxy/lib/ca.js'`

**Expected behavior**  
The adapter should start without this warning.

**Screenshots & Logfiles**  

Relevant log output:

```text
tuya.0  info starting. Version 3.18.1 in /opt/iobroker/node_modules/iobroker.tuya, node: v22.23.2, js-controller: 7.2.2
tuya.0  warn  Cannot patch http-mitm-proxy/lib/ca.js: Error: Cannot find module 'http-mitm-proxy/lib/ca.js'
Require stack:
- /opt/iobroker/node_modules/iobroker.tuya/main.js

tuya.0  info  Existing devices initialized
tuya.0  info  Try to sync devices from Cloud using stored cloud credentials
tuya.0  info  Listen for local Tuya devices on port 6666
tuya.0  info  Listen for encrypted local Tuya devices on port 6667
tuya.0  info  Cloud MQTT connection established successfully.
```

The installed http-mitm-proxy resolves to:

```text
/opt/iobroker/node_modules/http-mitm-proxy/dist/index.js
```

The CA implementation is located at:

```text
/opt/iobroker/node_modules/http-mitm-proxy/dist/lib/ca.js
```

There is no compiled:

```text
/opt/iobroker/node_modules/http-mitm-proxy/lib/ca.js
```

**Versions:**

Adapter version: 3.18.1
JS-Controller version: 7.2.2
Node version: 22.23.2
Operating system: Linux x64, Docker (buanet/iobroker:v11.1.0) on Synology DSM

**Additional context**
The affected code still contains the old workaround

https://github.com/Apollon77/ioBroker.tuya/blob/92a143416f14b6dc55b0ae5304bff51aaf923b79/main.js#L2357-L2376

With the currently installed http-mitm-proxy version, the compiled module is instead located at:

```text
http-mitm-proxy/dist/lib/ca.js
```

Additionally, http-mitm-proxy 1.1.0 appears to already generate certificates with a one-year validity. Therefore, the existing workaround which replaces:

```text
.validity.notBefore.getFullYear() + 2
```

with:

```text
.validity.notBefore.getFullYear() + 1
```

may no longer be necessary at all.

The warning does not currently seem to affect normal Tuya operation.

**Comment by Apollon77** [comment]
Good catch. Will fix

**Comment by Apollon77** [comment]
fixed by 3.18.2 released soon
